//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int UserId { get; set; }
        public string FullUrl { get; set; }
        public string ShortUrl { get; set; }
        public Nullable<int> ClicksNumber { get; set; }
    
        public virtual User User { get; set; }
    }
}
